### ISSUE TITLE
1.21版本样式加载不出来

### ISSUE THREAD

**Issue by disabilites** [censujiang/Mokore#11]
1.0版本没问题，1.2.1版本加载不出来

**Comment by censujiang** [comment]
请恢复主题默认设置

**Comment by disabilites** [comment]
启用后就这样了，已经是默认设置了吧
![捕获](https://user-images.githubusercontent.com/26649416/57980945-66b58080-7a64-11e9-92ec-45338bcc7e25.PNG)
