### ISSUE TITLE
希望可以添加文章滚动目录功能

### ISSUE THREAD

**Issue by HazukiKaguya** [censujiang/Mokore#7]
我基本照着这个来，勉强能用但是效果不是很理想。
https://blog.csdn.net/kongjiea/article/details/44017223

**Comment by censujiang** [comment]
已收到

**Comment by censujiang** [comment]
初步构思完毕，等待调试

**Comment by censujiang** [comment]
已实现

**Comment by HazukiKaguya** [comment]
nice

江程训 <notifications@github.com> 于 2019年2月13日周三 下午7:04写道：
